version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.0
    - 9.5.1
    - 9.5.2
  - dependency-name: filp/whoops
    versions:
    - 2.9.1
    - 2.9.2
  - dependency-name: laravel/framework
    versions:
    - 6.20.12
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
